/***********************************************************************
* This file is part of OpenMolcas.                                     *
*                                                                      *
* OpenMolcas is free software; you can redistribute it and/or modify   *
* it under the terms of the GNU Lesser General Public License, v. 2.1. *
* OpenMolcas is distributed in the hope that it will be useful, but it *
* is provided "as is" and without any express or implied warranties.   *
* For more details see the full text of the license in the file        *
* LICENSE or in <http://www.gnu.org/licenses/>.                        *
***********************************************************************/
#ifndef _MCPDFTFILES_
 (file)  MCPDFT        "$WorkDir/$Project$SubProject".McDens rw*st
 (file)  MCTRUD        "$WorkDir/$Project$SubProject".McTrue rw*st
#define _MCPDFTFILES_
#endif
