#include "aoints.inc"
#include "choints.inc"
#include "orbitals.inc"
#include "wfnfiles.inc"
 (file)  JOB001   "$WorkDir/$Project."JobIph      ro*
 (file)  JOB002   "$WorkDir/$Project."JobIph01    ro
 (file)  JOB003   "$WorkDir/$Project."JobIph02    ro
 (file)  JOB004   "$WorkDir/$Project."JobIph03    ro
 (file)  JOB005   "$WorkDir/$Project."JobIph04    ro
 (file)  JOB006   "$WorkDir/$Project."JobIph05    ro
 (file)  JOB007   "$WorkDir/$Project."JobIph06    ro
 (file)  JOB008   "$WorkDir/$Project."JobIph07    ro
 (file)  JOB009   "$WorkDir/$Project."JobIph08    ro
 (file)  JOB010   "$WorkDir/$Project."JobIph09    ro
 (file)  JOBIPH   "$WorkDir/$Project."JobIph      ro
 (file)  JOBIPH01 "$WorkDir/$Project."JobIph01    ro
 (file)  JOBIPH02 "$WorkDir/$Project."JobIph02    ro
 (file)  JOBIPH03 "$WorkDir/$Project."JobIph03    ro
 (file)  JOBIPH04 "$WorkDir/$Project."JobIph04    ro
 (file)  JOBIPH05 "$WorkDir/$Project."JobIph05    ro
 (file)  JOBIPH06 "$WorkDir/$Project."JobIph06    ro
 (file)  JOBIPH07 "$WorkDir/$Project."JobIph07    ro
 (file)  JOBIPH08 "$WorkDir/$Project."JobIph08    ro
 (file)  JOBIPH09 "$WorkDir/$Project."JobIph09    ro
 (file)  JOBIPH10 "$WorkDir/$Project."JobIph10    ro
 (file)  JOBMIX   "$WorkDir/$Project."JobMix      ro
 (file)  SCRATCH  "$WorkDir/"purge.tmp001         rw
 (file)  TDMFILE  "$WorkDir/"purge.tmp002         rw
 (file)  ANNI     "$WorkDir/"purge.tmp003         rw
 (file)  EXTRACT  "$WorkDir/$Project."Extract     rw
 (file)  TOFILE   "$WorkDir/$Project."ToFile      rw
 (file)  EIGV     "$WorkDir/$Project."EigV        rw
